/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MKL25Z128xxx4
package_id: MKL25Z128VLK4
mcu_data: ksdk2_0
processor_version: 9.0.0
board: FRDM-KL25Z
pin_labels:
- {pin_num: '30', pin_signal: TSI0_CH5/PTA4/I2C1_SDA/TPM0_CH1/NMI_b, label: 'J1[10]/D4', identifier: INB1_MOTO;INA2_MOTO;INA2_MOTOR;IN3_MOTOR}
- {pin_num: '31', pin_signal: PTA5/USB_CLKIN/TPM0_CH2, label: 'J1[12]/D5', identifier: PWM1_MOTOR}
- {pin_num: '33', pin_signal: PTA13/TPM1_CH1, label: 'J2[2]/D8', identifier: INB1_MOTOR;IN2_MOTOR}
- {pin_num: '45', pin_signal: ADC0_SE12/TSI0_CH7/PTB2/I2C0_SCL/TPM2_CH0, label: 'J10[6]/A2', identifier: CS1;CS1_MOTOR}
- {pin_num: '46', pin_signal: ADC0_SE13/TSI0_CH8/PTB3/I2C0_SDA/TPM2_CH1, label: 'J10[8]/A3', identifier: CS2;CS2_MOTOR}
- {pin_num: '58', pin_signal: PTC3/LLWU_P7/UART1_RX/TPM0_CH2/CLKOUTa, label: 'J1[5]', identifier: BT_RX}
- {pin_num: '61', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/TPM0_CH3, label: 'J1[7]', identifier: BT_TX}
- {pin_num: '62', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT, label: 'J1[9]', identifier: BT_EN}
- {pin_num: '65', pin_signal: CMP0_IN2/PTC8/I2C0_SCL/TPM0_CH4, label: 'J1[14]', identifier: PWM2_MOTOR}
- {pin_num: '66', pin_signal: CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5, label: 'J1[16]', identifier: INA1_MOTOR;IN1_MOTOR}
- {pin_num: '78', pin_signal: ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5, label: 'J2[4]/D9', identifier: INB2_MOTOR;IN4_MOTOR}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: '', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '28', peripheral: UART0, signal: TX, pin_signal: TSI0_CH3/PTA2/UART0_TX/TPM2_CH1}
  - {pin_num: '27', peripheral: UART0, signal: RX, pin_signal: TSI0_CH2/PTA1/UART0_RX/TPM2_CH0}
  - {pin_num: '66', peripheral: GPIOC, signal: 'GPIO, 9', pin_signal: CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5, identifier: IN1_MOTOR, direction: OUTPUT}
  - {pin_num: '33', peripheral: GPIOA, signal: 'GPIO, 13', pin_signal: PTA13/TPM1_CH1, identifier: IN2_MOTOR, direction: OUTPUT}
  - {pin_num: '30', peripheral: GPIOA, signal: 'GPIO, 4', pin_signal: TSI0_CH5/PTA4/I2C1_SDA/TPM0_CH1/NMI_b, identifier: IN3_MOTOR, direction: OUTPUT}
  - {pin_num: '78', peripheral: GPIOD, signal: 'GPIO, 5', pin_signal: ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5, identifier: IN4_MOTOR, direction: OUTPUT}
  - {pin_num: '31', peripheral: TPM0, signal: 'CH, 2', pin_signal: PTA5/USB_CLKIN/TPM0_CH2}
  - {pin_num: '65', peripheral: TPM0, signal: 'CH, 4', pin_signal: CMP0_IN2/PTC8/I2C0_SCL/TPM0_CH4}
  - {pin_num: '61', peripheral: UART1, signal: TX, pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/TPM0_CH3}
  - {pin_num: '58', peripheral: UART1, signal: RX, pin_signal: PTC3/LLWU_P7/UART1_RX/TPM0_CH2/CLKOUTa}
  - {pin_num: '62', peripheral: GPIOC, signal: 'GPIO, 5', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);

    gpio_pin_config_t IN3_MOTOR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA4 (pin 30)  */
    GPIO_PinInit(IN3_MOTOR_GPIO, IN3_MOTOR_PIN, &IN3_MOTOR_config);

    gpio_pin_config_t IN2_MOTOR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA13 (pin 33)  */
    GPIO_PinInit(IN2_MOTOR_GPIO, IN2_MOTOR_PIN, &IN2_MOTOR_config);

    gpio_pin_config_t IN1_MOTOR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC9 (pin 66)  */
    GPIO_PinInit(IN1_MOTOR_GPIO, IN1_MOTOR_PIN, &IN1_MOTOR_config);

    gpio_pin_config_t IN4_MOTOR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD5 (pin 78)  */
    GPIO_PinInit(IN4_MOTOR_GPIO, IN4_MOTOR_PIN, &IN4_MOTOR_config);

    /* PORTA1 (pin 27) is configured as UART0_RX */
    PORT_SetPinMux(DEBUG_UART_RX_PORT, DEBUG_UART_RX_PIN, kPORT_MuxAlt2);

    /* PORTA13 (pin 33) is configured as PTA13 */
    PORT_SetPinMux(IN2_MOTOR_PORT, IN2_MOTOR_PIN, kPORT_MuxAsGpio);

    /* PORTA2 (pin 28) is configured as UART0_TX */
    PORT_SetPinMux(DEBUG_UART_TX_PORT, DEBUG_UART_TX_PIN, kPORT_MuxAlt2);

    /* PORTA4 (pin 30) is configured as PTA4 */
    PORT_SetPinMux(IN3_MOTOR_PORT, IN3_MOTOR_PIN, kPORT_MuxAsGpio);

    /* PORTA5 (pin 31) is configured as TPM0_CH2 */
    PORT_SetPinMux(PWM1_MOTOR_PORT, PWM1_MOTOR_PIN, kPORT_MuxAlt3);

    /* PORTC3 (pin 58) is configured as UART1_RX */
    PORT_SetPinMux(BT_RX_PORT, BT_RX_PIN, kPORT_MuxAlt3);

    /* PORTC4 (pin 61) is configured as UART1_TX */
    PORT_SetPinMux(BT_TX_PORT, BT_TX_PIN, kPORT_MuxAlt3);

    /* PORTC5 (pin 62) is configured as PTC5 */
    PORT_SetPinMux(BT_EN_PORT, BT_EN_PIN, kPORT_MuxAsGpio);

    /* PORTC8 (pin 65) is configured as TPM0_CH4 */
    PORT_SetPinMux(PWM2_MOTOR_PORT, PWM2_MOTOR_PIN, kPORT_MuxAlt3);

    /* PORTC9 (pin 66) is configured as PTC9 */
    PORT_SetPinMux(IN1_MOTOR_PORT, IN1_MOTOR_PIN, kPORT_MuxAsGpio);

    /* PORTD5 (pin 78) is configured as PTD5 */
    PORT_SetPinMux(IN4_MOTOR_PORT, IN4_MOTOR_PIN, kPORT_MuxAsGpio);

    SIM->SOPT5 =
        ((SIM->SOPT5 &
          /* Mask bits to zero which are setting */
          (~(SIM_SOPT5_UART0TXSRC_MASK | SIM_SOPT5_UART0RXSRC_MASK | SIM_SOPT5_UART1TXSRC_MASK | SIM_SOPT5_UART1RXSRC_MASK)))

         /* UART0 transmit data source select: UART0_TX pin. */
         | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX)

         /* UART0 receive data source select: UART0_RX pin. */
         | SIM_SOPT5_UART0RXSRC(SOPT5_UART0RXSRC_UART_RX)

         /* UART1 transmit data source select: UART1_TX pin. */
         | SIM_SOPT5_UART1TXSRC(SOPT5_UART1TXSRC_UART_TX)

         /* UART1 receive data source select: UART1_RX pin. */
         | SIM_SOPT5_UART1RXSRC(SOPT5_UART1RXSRC_UART_RX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
